trigger:
- master

jobs:
- job: Mojave
  displayName: 'Mojave'
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: ./test.sh
    displayName: test script

- job: Catalina
  displayName: 'Catalina'
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - script: ./test.sh
    displayName: test script
    