trigger:
- master

jobs:
- job: test
  displayName: 'test'
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: ./test.sh
    displayName: test script

- job: test
  displayName: 'test'
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - script: ./test.sh
    displayName: test script
    