trigger:
- master

jobs:
- job: macOS
  strategy:
    matrix:
      Sonoma:
        vmImage: 'macOS-14'
      Sequoia:
        vmImage: 'macOS-15'
      Tahoe:
        vmImage: 'macOS-26'
  displayName: 'macOS'
  pool:
    vmImage: $(vmImage)
  steps:
  - script: ./test.sh
    displayName: test script
  - script: |
      mkdir -p /Users/runner/sysdiagnose
      sudo sysdiagnose -ub -f /Users/runner/sysdiagnose -A sysdiagnose_$(System.JobPositionInPhase)
    displayName: 'Collect sysdiagnose'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish sysdiagnose'
    inputs:
      pathtoPublish: /Users/runner/sysdiagnose/
      artifactName: sysdiagnose
