trigger:
- master

jobs:
- job: macOS
  strategy:
    matrix:
      Tahoe:
        vmImage: 'macOS-26'
        legName: 'Tahoe'
  displayName: 'macOS'
  pool:
    vmImage: $(vmImage)
  steps:
  - script: ./test.sh
    displayName: test script
  - script: |
      mkdir -p /Users/runner/logs
      sudo log collect --start "$(cat /Users/runner/test-start-time)" --output /Users/runner/logs/system_logs_$(legName).logarchive
    displayName: 'Collect logs'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish logs'
    inputs:
      pathtoPublish: /Users/runner/logs/
      artifactName: logs
